// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8HmgVkadcIddu9zA8BaxAnfDkOqdD4ek',
    appId: '1:88612313525:web:235a4466fdbbcc3e80a1fc',
    messagingSenderId: '88612313525',
    projectId: 'curator-70a66',
    authDomain: 'curator-70a66.firebaseapp.com',
    storageBucket: 'curator-70a66.firebasestorage.app',
    measurementId: 'G-WNYYRTF01E',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCKOp4_mNO2QZTAtWwtgvrtzvN7dmC8U7I',
    appId: '1:88612313525:android:5cf564d752fa25f780a1fc',
    messagingSenderId: '88612313525',
    projectId: 'curator-70a66',
    storageBucket: 'curator-70a66.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPv3T5z5cYkJF82UOFAGNwBmxfVNt_Rag',
    appId: '1:88612313525:ios:6e345bc4ee5dbdc780a1fc',
    messagingSenderId: '88612313525',
    projectId: 'curator-70a66',
    storageBucket: 'curator-70a66.firebasestorage.app',
    iosBundleId: 'com.example.polaroidGalleryApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPv3T5z5cYkJF82UOFAGNwBmxfVNt_Rag',
    appId: '1:88612313525:ios:6e345bc4ee5dbdc780a1fc',
    messagingSenderId: '88612313525',
    projectId: 'curator-70a66',
    storageBucket: 'curator-70a66.firebasestorage.app',
    iosBundleId: 'com.example.polaroidGalleryApp',
  );
}
